### ISSUE TITLE
Shuusaku

### ISSUE THREAD

**Issue by zsolszesz** [TesterTesterov/AI5WINArcTool#4]
Hey,
I was trying to use your AI5WIN tools with the game, Shuusaku, but unfortunately it's not compatible with it. I believe it uses a modified version of the engine. I uploaded the game here: https://drive.google.com/file/d/148Git02yIaudEFV8_1gvxlf6KQZqcPY8/view  I would really appreciate, if you could take a look sometime.
Some russian guys attempted to make a translation many years ago, and made some tools for it which can be found here: http://zz-uu.narod.ru/downloads.htm
The source codes might provide some info about the game. Unfortunately, their mega tool is far from perfect.

**Comment by TesterTesterov** [comment]
I have looked on it. And... This one is not an AI5. This is some sort of AI system, but not AI1-6 or Silky Engine. I saw one game on similar system (AI SYSTEM 6, one is not AI6WIN). This one is... Well, as I saw in .exe file, some "AIW". These systems can often be found in DVD editions. Ideally, I wouldn't recommend you to technically work with this one, as it's script, unlike AI SYSTEM 6's, is some sort of unknown variation, which would be quite tiresome to hack. Or I just hacked the archives wrong?..

**Also, can you say, which edition of the game you uploaded here from [these](https://vndb.org/v1130)?**

Anyway, as it is not an AI5WIN, and the archives themselves are quite easy to hack, I'll drop the tool here: [AIWArcTool.zip](https://github.com/TesterTesterov/AI5WINArcTool/files/9956962/AIWArcTool.zip). Try it out.
Do note, I could make some mistake considering the encryption of the files... But, as I tried some methods, this is the one with the most probability. Still, I cannot guarantee, as MES does not work anyway.

**Comment by zsolszesz** [comment]
Thanks for the quick reply, I'll try it out. I found this version which supposed to be the DVD edition. I also found one, where the person stated it was the DMM edition, but the MES was exactly the same. I was looking everywhere for the CD edition, but I wasn't able to find it, unfortunately.

**Comment by zsolszesz** [comment]
Well I found the CD version, but it seems like it uses the same engine, and there are only minor differences from what I've seen. Like less sound calls, since the protagonist isn't voiced in the CD version. I uploaded it if you wish to take a look: https://drive.google.com/file/d/1gPMid63y_BYtuYrLIB_B0HkEleKmDTqu/view?usp=sharing
