### ISSUE TITLE
cp932 codec can't decode byte 0xf4 in position 15: illegal multibyte sequence

### ISSUE THREAD

**Issue by JackDBS** [TesterTesterov/AI5WINArcTool#5]
I've been having this error come up with the MES tool multiple times. I've tested Isaku Renewal, Doukyuusei 99, and Be-Yond. All of them don't extract to txt files. On the ARC tool, the keys files doesn't extract oddly and I get an error there.

**Comment by TesterTesterov** [comment]
@JackDBS, to be more precise, the MES tool does not **extract** to the txt files, it creates a disassembled representation in the txt file.
Post here sample MES and ARC, which does not work. I shall check them as I have time.

**Comment by JackDBS** [comment]
Yes I know that it shows a decompiled version of the file. I've used these kind of programs before. The problem is that is doesn't even extract to TXT files. It just gives me an error and that's it. No TXT files. I've tested all of these files: https://drive.google.com/drive/folders/1f58uBX10XtIk5Jra_n3Cpi1pfKJCArPj?usp=sharing

Isaku Renewal by the way

**Comment by TesterTesterov** [comment]
@JackDBS, no problems whatsoever.

![Снимок](https://user-images.githubusercontent.com/66121918/209431012-8b1c3b5b-f337-4e43-b5b3-ef6290343fe9.JPG)
